---
# @author Anthony Loukinas <anthony.loukinas@redhat.com>

- name: Create environment build directory
  file:
    path: "{{ playbook_dir }}/build/{{ tower_environment }}"
    state: directory

- name: Create templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ playbook_dir }}/build/{{ tower_environment }}/{{ item }}"
  loop:
    - docker-compose.yml
    - environment.sh
    - SECRET_KEY
    - settings.py
    - credentials.py