---

version: '3'

services:
  web:
    image: quay.io/ansible-tower/ansible-tower:3.6.1
    container_name: tower_web
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    hostname: awx_web
    user: root
    restart: unless-stopped
    ports:
      - 80:8052
    volumes:
      - "./assets/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./assets/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./assets/settings.py:/etc/tower/settings.py"
      - "./assets/credentials.py:/etc/tower/conf.d/credentials.py"

  task:
    image: quay.io/ansible-tower/ansible-tower:3.6.1
    container_name: tower_task
    command: /usr/bin/launch_awx_task.sh
    depends_on:
      - rabbitmq
      - memcached
      - postgres
      - web
    # https://github.com/ansible/awx/issues/86#issuecomment-331923704
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "./assets/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./assets/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./assets/settings.py:/etc/tower/settings.py"
      - "./assets/credentials.py:/etc/tower/conf.d/credentials.py"

  rabbitmq:
    image: ansible/awx_rabbitmq:3.7.4
    container_name: tower_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "awx"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_ERLANG_COOKIE: cookiemonster

  memcached:
    image: memcached:alpine
    container_name: tower_memcached
    restart: unless-stopped

  postgres:
    image: postgres:9.6
    container_name: tower_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - tower_db:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  tower_db:
    external: true